{{- if not .Values.podStrategy.singlePod }}
{{- $fullName := include "goosed-ui.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-web
  labels:
    {{- include "goosed-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullName }}-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $fullName }}-web
        {{- include "goosed-ui.labels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}
{{- end }}
