{{- $fullName := include "goosed-ui.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret
  labels:
    {{- include "goosed-ui.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.config.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
