{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "goosed-pxe-stack.serviceAccountName" . }}
  labels:
    {{- include "goosed-pxe-stack.labels" . | nindent 4 }}
{{- end }}
