image:
  repository: goosed/api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

otel:
  exporterEndpoint: http://otel-collector:4318

env: {}

ingress:
  enabled: true
  className: ""
  annotations: {}
  host: api.goose.local
  tlsSecretName: goosed-api-selfsigned

resources: {}

affinity: {}

tolerations: []

nodeSelector: {}
